/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.woon;

import java.awt.Frame;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.lang.reflect.Array;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author eusea
 */
public class AddBookingDialog extends javax.swing.JDialog {

    int roomNumber;
    boolean isChangesMade = false;

    /**
     * Creates new form AddBookingDialog
     */
    public AddBookingDialog(java.awt.Frame parent, boolean modal, int roomNumber) {
        super(parent, modal);
        this.roomNumber = roomNumber;
        initComponents();
        this.setTitle("Add Booking (Room " + roomNumber + ") - Hotel Manager");

        lblRoomNumber.setText(String.valueOf(roomNumber));

        try {
            for (Integer i : MenuFrame.bookingData.getDaysBooked(roomNumber)) {
                JCheckBox bookedCheckBox = ReflectionUtil.getComponentByType(JCheckBox.class, "cb" + BookingData.dayToString(i), this);
                bookedCheckBox.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        DocumentListener textChangedListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                setDirty();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                setDirty();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                setDirty();
            }

            public void setDirty() {
                if (isChangesMade == false) {
                    isChangesMade = true;
                    setTitle(getTitle() + " *");
                }
            }
        };

        ActionListener checkBoxCheckedListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (isChangesMade == false) {
                    isChangesMade = true;
                    setTitle(getTitle() + " *");
                }
            }
        };

        try {
            for (JTextField textBox : ReflectionUtil.getComponentsByType(JTextField.class, this)) {
                textBox.getDocument().addDocumentListener(textChangedListener);
            }
            for (JCheckBox checkBox : ReflectionUtil.getComponentsByType(JCheckBox.class, this)) {
                checkBox.addActionListener(checkBoxCheckedListener);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblRoomNumber = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbMonday = new javax.swing.JCheckBox();
        cbTuesday = new javax.swing.JCheckBox();
        cbWednesday = new javax.swing.JCheckBox();
        cbThursday = new javax.swing.JCheckBox();
        cbSunday = new javax.swing.JCheckBox();
        cbSaturday = new javax.swing.JCheckBox();
        cbFriday = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        txtCustomerFName = new javax.swing.JTextField();
        txtCustomerLName = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        txtIdentityCard = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hotel Manager - Add Booking");

        jPanel1.setPreferredSize(new java.awt.Dimension(1152, 678));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Room Number:");

        lblRoomNumber.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblRoomNumber.setText("000");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Customer First Name:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Customer Last Name:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setText("IC/Passport Number");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setText("Contact Number:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setText("Email: ");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setText("Days Booked:");

        cbMonday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbMonday.setText("Monday");
        cbMonday.setName("cbMonday"); // NOI18N

        cbTuesday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbTuesday.setText("Tuesday");

        cbWednesday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbWednesday.setText("Wednesday");

        cbThursday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbThursday.setText("Thursday");

        cbSunday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbSunday.setText("Sunday");

        cbSaturday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbSaturday.setText("Saturday");

        cbFriday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbFriday.setText("Friday");

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSave.setText("Add Booking");
        btnSave.setPreferredSize(new java.awt.Dimension(150, 50));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtCustomerFName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCustomerFName.setMinimumSize(new java.awt.Dimension(15, 35));

        txtCustomerLName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCustomerLName.setMinimumSize(new java.awt.Dimension(15, 35));

        txtContactNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtContactNumber.setMinimumSize(new java.awt.Dimension(15, 35));

        txtIdentityCard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtIdentityCard.setMinimumSize(new java.awt.Dimension(15, 35));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEmail.setMinimumSize(new java.awt.Dimension(15, 35));

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setText("Discard");
        btnCancel.setPreferredSize(new java.awt.Dimension(150, 50));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRoomNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCustomerFName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCustomerLName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtContactNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdentityCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 834, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbThursday)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTuesday)
                                    .addComponent(cbWednesday)
                                    .addComponent(cbMonday))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbFriday)
                                    .addComponent(cbSaturday)
                                    .addComponent(cbSunday))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRoomNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCustomerFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCustomerLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdentityCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMonday)
                    .addComponent(cbFriday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTuesday)
                    .addComponent(cbSaturday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbWednesday)
                    .addComponent(cbSunday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbThursday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        ArrayList<String> inputErrors = checkErrors();
        if (inputErrors.size() > 0) {
            // How to join array
            // https://stackoverflow.com/questions/599161/best-way-to-convert-an-arraylist-to-a-string

            String errorMessage = String.join("\n", inputErrors);
            JOptionPane.showMessageDialog(this, "There are input errors:\n" + errorMessage, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        CustomerData newCustomer = new CustomerData(
                txtCustomerFName.getText().trim(), txtCustomerLName.getText().trim(),
                txtIdentityCard.getText().trim().toUpperCase(), txtContactNumber.getText().trim(),
                txtEmail.getText().trim()
        );

        int[] daysBooked = {};
        JCheckBox[] dayCheckboxes = {};

        try {
            dayCheckboxes = ReflectionUtil.getComponentsByType(JCheckBox.class, this);
        } catch (Exception e) {
            e.printStackTrace();
            return;
        }

        int checked = 0;
        for (JCheckBox dayCheckbox : dayCheckboxes) {
            if (dayCheckbox.isSelected()) {
                checked++;
            }
        }

        if (checked <= 0) {
            JOptionPane.showMessageDialog(this, "Please select atleast one day", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        daysBooked = (int[]) Array.newInstance(int.class, checked);

        int currentCheckbox = 0;
        for (JCheckBox dayCheckbox : dayCheckboxes) {
            if (dayCheckbox.isSelected()) {
                daysBooked[currentCheckbox++] = BookingData.stringToDay(dayCheckbox.getText());
            }
        }

        BookingData newBookingData = new BookingData(newCustomer, Integer.valueOf(lblRoomNumber.getText()), true, daysBooked);

        ReceiptDialog receipt = new ReceiptDialog((Frame) SwingUtilities.getWindowAncestor(this), true, newBookingData);
        receipt.setVisible(true);

        if (receipt.getResponse() == false) {
            JOptionPane.showConfirmDialog(this, "Payment cancelled.", "Info", JOptionPane.OK_OPTION);
            return;
        } else {
            JOptionPane.showConfirmDialog(this, "Payment successful.", "Success", JOptionPane.OK_OPTION);
        }

        MenuFrame.bookings.add(newBookingData);

        SaveData.saveBookingData();
        MenuFrame.refreshTable();
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (isChangesMade) {
            int result = JOptionPane.showConfirmDialog(this, "You have unsaved changes. Discard changes?", "Info", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                MenuFrame.refreshTable();
                this.dispose();
            }
        } else {
            MenuFrame.refreshTable();
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private ArrayList<String> checkErrors() {
        ArrayList<String> listOfErrors = new ArrayList<>();

        if (txtCustomerFName.getText().trim().isBlank()
                || txtCustomerLName.getText().trim().isBlank()
                || txtIdentityCard.getText().trim().isBlank()
                || txtContactNumber.getText().trim().isBlank()
                || txtEmail.getText().trim().isBlank()) {
            listOfErrors.add("Please fill up all fields!");
            return listOfErrors;
        } else {

            // how to regex passport number
            // https://stackoverflow.com/questions/40647728/regex-for-passport-number
            if (!txtIdentityCard.getText().trim().toUpperCase().matches("^[A-Z]{1,3}\\d+(\\w|)$") && !txtIdentityCard.getText().matches("^\\d{6}(-|)\\d{2}(-|)\\d{4}$")) {
                listOfErrors.add("Passport/IC number is invalid!");
            }

            if (!txtContactNumber.getText().trim().matches("^(01)\\d-\\d{7,8}$")) {
                listOfErrors.add("Contact number must follow the format: 01X-XXXXXXX!");
            }

            // Email regex
            // https://regexr.com/2ri2c
            if (!txtEmail.getText().trim().matches("\\b[\\w\\.-]+@[\\w\\.-]+\\.\\w{2,4}\\b")) {
                listOfErrors.add("Email provided is in invalid format!");
            }

            return listOfErrors;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancel;
    public javax.swing.JButton btnSave;
    public javax.swing.JCheckBox cbFriday;
    public javax.swing.JCheckBox cbMonday;
    public javax.swing.JCheckBox cbSaturday;
    public javax.swing.JCheckBox cbSunday;
    public javax.swing.JCheckBox cbThursday;
    public javax.swing.JCheckBox cbTuesday;
    public javax.swing.JCheckBox cbWednesday;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblRoomNumber;
    public javax.swing.JTextField txtContactNumber;
    public javax.swing.JTextField txtCustomerFName;
    public javax.swing.JTextField txtCustomerLName;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtIdentityCard;
    // End of variables declaration//GEN-END:variables
}
